# -*- coding: utf-8 -*-
"""RBS_Graphs.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lSDjd_ANKi2ZhhOujbqQM6yViNKNphFI
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

data1 = pd.read_csv('473012P0.csv',names=['Spetra','lattice'])
data1.head()

data2 = pd.read_csv('473012R1.csv',names=['Spetra','lattice'])
data2.head()

data3 = pd.read_csv('473013P0.csv',names=['Spetra','lattice'])
data3.head()

data4 = pd.read_csv('473013R1.csv',names=['Spetra','lattice'])
data4.head()

data5 = pd.read_csv('473014P0.csv',names=['Spetra','lattice'])
data5.head()

data6 = pd.read_csv('473014R1.csv',names=['Spetra','lattice'])
data6.head()

data7 = pd.read_csv('473015P0.csv',names=['Spetra','lattice'])
data7.head()

data8 = pd.read_csv('473015R1.csv',names=['Spetra','lattice'])
data8.head()

data9 = pd.read_csv('473016P0.csv',names=['Spetra','lattice'])
data9.head()

data10 = pd.read_csv('473016R1.csv',names=['Spetra','lattice'])
data10.head()

plt.plot(data1.Spetra , data1.lattice)
plt.title("473012P0.csv")
plt.xlabel("counts")
plt.ylabel("Enegry(keV)")
plt.savefig('473012P0_Graph.png')
plt.show()

plt.plot(data2.Spetra , data2.lattice)
plt.title("473012R1.csv")
plt.xlabel("counts")
plt.ylabel("Enegry(keV)")
plt.xlim([0, 2000])
plt.savefig('473012R1_Graph.png')
plt.show()

plt.plot(data3.Spetra , data3.lattice)
plt.title("473013P0.csv")
plt.xlabel("counts")
plt.ylabel("Enegry(keV)")
plt.savefig('473013P0_Graph.png')
plt.show()

plt.plot(data4.Spetra , data4.lattice)
plt.title("473013R1.csv")
plt.xlabel("counts")
plt.ylabel("Enegry(keV)")
plt.xlim([0, 2000])
plt.savefig('473013R1_Graph.png')
plt.show()

plt.plot(data5.Spetra , data5.lattice)
plt.title("473014P0.csv")
plt.xlabel("counts")
plt.ylabel("Enegry(keV)")
plt.savefig('473014P0_Graph.png')
plt.show()

plt.plot(data6.Spetra , data6.lattice)
plt.title("473014R1.csv")
plt.xlabel("counts")
plt.ylabel("Enegry(keV)")
plt.xlim([0, 2000])
plt.savefig('473014R1_Graph.png')
plt.show()

plt.plot(data7.Spetra , data7.lattice)
plt.title("473015P0.csv")
plt.xlabel("counts")
plt.ylabel("Enegry(keV)")
plt.savefig('473015P0_Graph.png')
plt.show()

plt.plot(data8.Spetra , data8.lattice)
plt.title("473015R1.csv")
plt.xlabel("counts")
plt.ylabel("Enegry(keV)")
plt.xlim([0, 2000])
plt.savefig('473015R1_Graph.png')
plt.show()

plt.plot(data9.Spetra , data9.lattice)
plt.title("473016P0.csv")
plt.xlabel("counts")
plt.ylabel("Enegry(keV)")
plt.savefig('473016P0_Graph.png')
plt.show()

plt.plot(data10.Spetra , data10.lattice)
plt.title("473016R1.csv")
plt.xlabel("counts")
plt.ylabel("Enegry(keV)")
plt.xlim([0, 2000])
plt.savefig('473016R1_Graph.png')
plt.show()